import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import { gzipSync } from 'node:zlib';
import { build as bundle } from 'esbuild';
const root = process.cwd();
const require = createRequire(path.join(root,'apps/openassist-cli/package.json'));
const tar = require('tar');
const output = path.resolve(process.argv[2] ?? 'coverage/release');
const target = `${process.platform}-${process.arch}`;
if (!['linux-x64','linux-arm64','darwin-x64','darwin-arm64'].includes(target)) throw new Error('Package on a native supported Linux/macOS architecture.');
if (process.versions.node !== '24.21.0') throw new Error('Release packaging requires the pinned Node 24.21.0 runtime.');
const run = (cmd,args) => { const r = spawnSync(cmd,args,{cwd:root,stdio:'inherit'}); if(r.status !== 0) throw new Error(`${cmd} failed`); };
const commit = spawnSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).stdout.trim();
const version = JSON.parse(fs.readFileSync('package.json','utf8')).version;
if (process.env.RELEASE_TAG && process.env.RELEASE_TAG !== `v${version}`) throw new Error('Release tag must match package.json version.');
const stage = path.join(output,`stage-${target}`);
if(fs.existsSync(stage)) throw new Error('Packaging stage already exists; use a new output directory.');
fs.mkdirSync(stage,{recursive:true});
for(const app of ['openassist-cli','openassistd']) run('pnpm',['--filter',`@openassist/${app}`,'--prod','deploy',path.join(stage,'apps',app)]);
for(const name of ['docs','deploy']) fs.cpSync(path.join(root,name),path.join(stage,name),{recursive:true});
for(const name of ['release-public.pem','README.md','CHANGELOG.md','LICENSE']) if(fs.existsSync(name)) fs.copyFileSync(name,path.join(stage,name));
fs.mkdirSync(path.join(stage,'runtime','bin'),{recursive:true});
fs.copyFileSync(process.execPath,path.join(stage,'runtime','bin','node'));
fs.chmodSync(path.join(stage,'runtime','bin','node'),0o755);
const build = {id:`${version}-${commit}`,version,commit,nodeVersion:process.versions.node,configVersion:1,databaseVersion:1};
fs.writeFileSync(path.join(stage,'build-identity.json'),JSON.stringify(build,null,2));
for(const app of ['openassist-cli','openassistd']) run(path.join(stage,'runtime','bin','node'),[path.join(stage,'apps',app,'dist','index.js'),'--help']);
const file = `openassist-${version}-${target}.tar.gz`;
tar.c({gzip:true,sync:true,file:path.join(output,file),cwd:stage,portable:true},fs.readdirSync(stage));
const bytes = fs.readFileSync(path.join(output,file));
const artifact = {platform:process.platform,arch:process.arch,file,sha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length};
// Bootstrap executes only these individually authenticated files before extraction.
const runtimeFile = `bootstrap-node-${target}.gz`;
fs.writeFileSync(path.join(output,runtimeFile),gzipSync(fs.readFileSync(process.execPath)));
const verifierFile = `bootstrap-verifier-${target}.mjs`;
await bundle({entryPoints:['scripts/release/bootstrap-verifier.ts'],outfile:path.join(output,verifierFile),bundle:true,platform:'node',format:'esm',target:'node24',banner:{js:"import { createRequire } from 'node:module'; const require = createRequire(import.meta.url);"}});
const metadata = name => {const data=fs.readFileSync(path.join(output,name));return {file:name,sha256:createHash('sha256').update(data).digest('hex'),bytes:data.length};};
artifact.bootstrap = {runtime:metadata(runtimeFile),verifier:metadata(verifierFile)};
fs.writeFileSync(path.join(output,`${target}.json`),JSON.stringify({build,artifact},null,2));
console.log(JSON.stringify({stage,artifact}));
